services:
  - type: web
    name: music-pdf-manager
    env: static
    buildCommand: ""
    staticPublishPath: .
    headers:
      # Permitir scripts de Google y PDF.js
      - path: "/*.js"
        name: "Content-Type"
        value: "application/javascript; charset=utf-8"
      # Permitir CSS
      - path: "/*.css"
        name: "Content-Type" 
        value: "text/css; charset=utf-8"
      # CSP corregida para Google Drive
      - path: "/*"
        name: "Content-Security-Policy"
        value: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://apis.google.com https://accounts.google.com https://www.gstatic.com https://cdnjs.cloudflare.com data: blob:; connect-src 'self' https://www.googleapis.com https://accounts.google.com https://oauth2.googleapis.com https://content.googleapis.com https://www.google.com https://drive.google.com https://lh3.googleusercontent.com; frame-src 'self' https://accounts.google.com https://drive.google.com https://docs.google.com https://content.googleapis.com; img-src 'self' data: https: blob:; style-src 'self' 'unsafe-inline' https:; font-src 'self' https: data:; object-src 'none'; base-uri 'self';"
      # Headers de seguridad
      - path: "/*"
        name: "X-Frame-Options"
        value: "SAMEORIGIN"
      - path: "/*"
        name: "X-Content-Type-Options"
        value: "nosniff"
      # CORS para APIs de Google - más permisivo
      - path: "/*"
        name: "Access-Control-Allow-Origin"
        value: "*"
      - path: "/*"
        name: "Access-Control-Allow-Methods"
        value: "GET, POST, OPTIONS, HEAD"
      - path: "/*"
        name: "Access-Control-Allow-Headers"
        value: "Content-Type, Authorization, X-Requested-With"
      # Headers adicionales para Google Drive
      - path: "/*"
        name: "Cross-Origin-Opener-Policy"
        value: "same-origin-allow-popups"
      - path: "/*"
        name: "Cross-Origin-Embedder-Policy"
        value: "unsafe-none"
    routes:
      # SPA routing
      - type: rewrite
        source: "/((?!.*\\.).*)"
        destination: "/index.html"